### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Laurick**
## 1. Why?
For statibily prupouses I think is a good idea use a lib to make some tests.

## 2. How?
Using GUT, which is a unit testing ib for godot, I setup the proyect, made the first tests and made some fixes

## 3. Related Issue

#8

## 4. Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## 5. Tests made (if appropriate)
all

## 6. Notes (if appropriate)
I know its a HUGE PR but I can't make it smaller

### CODE REVIEW

**Comment by Laurick** [comment]
Hey @rothiotome I was working on testing and I would like you to give me your opinion about it. You can check the changes but let me explain in a few points the work so far:

* I Added GUT addon 😎 
* Added 2 test files for check some static methods
* Added some comments in files
* Linter fixes
* Added a raw documentation WIP
* Added also an action. The limits for a free account are 2000 minutes each month and 500 GB of space
    - Unfortunately https://www.tuxfamily.org/ is down so the automatic test are broken now ( yay 😢 )

**Comment by Laurick** [comment]
Hey Rothio, job done (?)

I want to test the action but for that I need to close thisPR and open a new one. Are you ok with this?

**Comment by Laurick** [comment]
Remove both "fixme"s. It was a dumb error with breaking lines in godot editor ( duh ). I added a strip_edges for safetines

Good catch!

**Review by rothiotome — APPROVED** [review]
Everything seems fine. Great addition to the plugin :D

**Pull request merged**
